# Generated by Django 5.1.1 on 2024-09-22 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_de_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_renda', models.CharField(max_length=100)),
                ('valor_da_renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendas', to='conta.perfil_de_usuario')),
            ],
        ),
    ]
