# Generated by Django 5.1.1 on 2024-09-22 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_despesa', models.CharField(max_length=100)),
                ('valor_da_despesa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('mercado', 'Mercado'), ('transporte', 'Transporte'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('habitacao', 'Habitação'), ('pessoais', 'Despesas Pessoais'), ('lazer', 'Lazer'), ('outros', 'Outros')], max_length=20)),
                ('data_do_gasto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Despesa_prestação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_de_parcelas', models.IntegerField()),
                ('despesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historico.despesas')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa_fixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fim_fixa', models.DateField()),
                ('despesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historico.despesas')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('total_renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_gastos', to='conta.perfil_de_usuario')),
            ],
        ),
        migrations.AddField(
            model_name='despesas',
            name='historico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='historico.historico_gastos'),
        ),
    ]
